language: php

php:
    - 5.4
    - 5.5
    - 5.6

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=2.6.*
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*

services:
    - mongodb

before_script:
    - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - curl -s http://getcomposer.org/installer | php
    - composer require symfony/symfony:${SYMFONY_VERSION}
    - php -d memory_limit=-1 composer.phar install
    - php Tests/app/console generate:rest:controller -t --controller TestTestBundle:MyCar --entity TestTestBundle:Car
    - php Tests/app/console generate:rest:controller -t --controller TestTestBundle:MyCarOwner --entity TestTestBundle:CarOwner
    - php Tests/app/console doctrine:database:create
    - php Tests/app/console doctrine:schema:create
    - php -S 127.0.0.1:8888 -t Tests Tests/app_test.php &
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - phantomjs --web-security=no Tests/testrunner.js http://127.0.0.1:8888/SpecRunner.html
    - php Tests/app/console doctrine:database:drop --force
    - phpunit -c phpunit.xml.dist