extjs_generate_model:
    pattern:   /generateModel.js
    defaults:  { _controller: TpgExtjsBundle:Generator:generateModel }

extjs_remote_api:
    pattern:   /remoteapi.js
    defaults:  { _controller: TpgExtjsBundle:Generator:generateRemoteApi }